
global MANIPULATED_AUDIO_FOLDER
MANIPULATED_AUDIO_FOLDER = 'Audio/ManipulatedAudioFiles'
global ORIGINAL_AUDIO_FOLDER
ORIGINAL_AUDIO_FOLDER = 'Audio/OriginalAudioFiles'
global SPECIES_IMAGES_FOLDER
SPECIES_IMAGES_FOLDER = 'Images/Species'
